[general]
import = [ "themes/tokyo-night/tokyo-night.toml" ]

[font]
normal = { family = "Monaspace Krypton", style = "Regular"}
size = 12

[window]
opacity = 0.9

# Disable alacritty vim mode
[[keyboard.bindings]]
key = "Space"
mods = "Control|Shift"
action = "ReceiveChar"
